package com.urlshortener.dto.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * =====================================================
 * REGISTER REQUEST DTO
 * =====================================================
 *
 * WHAT IS A DTO (Data Transfer Object)?
 * ──────────────────────────────────────
 * A DTO is a simple Java object that carries data between layers.
 * It defines the EXACT SHAPE of data the client must send.
 *
 * WHY NOT USE THE USER ENTITY DIRECTLY?
 * ──────────────────────────────────────
 * This is a critical design decision. Here's why we need separate DTOs:
 *
 * 1. SECURITY — The User entity has fields the client should NEVER set:
 *    - id (auto-generated by DB)
 *    - role (set by server, not by user — otherwise anyone becomes ADMIN!)
 *    - createdAt, updatedAt (auto-managed)
 *    If we accept User directly, a malicious client could send:
 *    { "username": "hacker", "role": "ADMIN" }  ← DANGEROUS!
 *
 * 2. DECOUPLING — If we change the User entity (add fields, rename columns),
 *    the API contract stays stable. Clients don't break.
 *
 * 3. VALIDATION — DTOs have validation rules specific to the API.
 *    The entity has DB constraints. These are different concerns.
 *    Example: DTO validates password length (6-100 chars).
 *             Entity doesn't even store the raw password (it's hashed).
 *
 * 4. CLARITY — The DTO documents exactly what the API expects.
 *    When a frontend developer sees this class, they know exactly
 *    what JSON to send. No ambiguity.
 *
 * REQUEST JSON EXAMPLE:
 * {
 *   "username": "john_doe",
 *   "email": "john@example.com",
 *   "password": "securePassword123"
 * }
 *
 * LOMBOK: @Data = @Getter + @Setter + @ToString + @EqualsAndHashCode
 * It's a shortcut that generates ALL common boilerplate methods.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RegisterRequest {

    /*
     * @NotBlank → Validates that the field is:
     *   1. Not null
     *   2. Not empty ("")
     *   3. Not just whitespace ("   ")
     *
     *   Different from @NotNull (allows "") and @NotEmpty (allows "   ").
     *   @NotBlank is the strictest — it's what you want for usernames.
     *
     * @Size(min = 3, max = 50)
     *   → Username must be between 3 and 50 characters.
     *   Why min 3? Single-character usernames are confusing.
     *   Why max 50? Matches the DB column length (VARCHAR(50)).
     *
     * message = "..." → Custom error message returned to the client
     *   when validation fails. Without this, Spring returns a generic
     *   "must not be blank" which isn't very helpful.
     *
     * HOW VALIDATION WORKS:
     *   1. Client sends JSON → Spring deserializes to RegisterRequest
     *   2. If controller parameter has @Valid annotation,
     *      Spring checks ALL validation annotations on each field
     *   3. If any validation fails → Spring throws MethodArgumentNotValidException
     *   4. Our exception handler catches it → Returns a clean error response
     *   5. The controller method NEVER executes with invalid data
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    private String username;

    /*
     * @Email → Validates that the string is a properly formatted email.
     *   Uses a regex pattern internally to check format.
     *   Valid: "john@example.com", "user.name+tag@domain.co"
     *   Invalid: "john", "john@", "@example.com", "john @example.com"
     *
     * NOTE: @Email only validates FORMAT, not existence.
     * "nonexistent@fake-domain-xyz.com" passes @Email validation.
     * To verify the email actually exists, you'd need to send
     * a verification email (out of scope for now).
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Please provide a valid email address")
    @Size(max = 100, message = "Email must not exceed 100 characters")
    private String email;

    /*
     * Password validation:
     *   min = 6  → Minimum security requirement
     *   max = 100 → Prevent abuse (extremely long passwords)
     *
     * NOTE: This is the RAW password from the client.
     * It will be HASHED with BCrypt before storing in the database.
     * The raw password is NEVER stored anywhere.
     *
     * In a production app, you might add more password rules:
     *   - Must contain uppercase letter
     *   - Must contain number
     *   - Must contain special character
     * These would use a custom @Password validator annotation.
     */
    @NotBlank(message = "Password is required")
    @Size(min = 6, max = 100, message = "Password must be between 6 and 100 characters")
    private String password;
}
